# this script will be used to conduct exploratory factor analysis
# I will pay some attention to a potential four factor model to see if it might align with the findings generated by FEMA

# load data
nhs <- read.csv("nhs-clean.csv") |> 
  dplyr::select(
    dis_prep, 
    dis_soc, 
    dis_exp, 
    dis_perception,
    dis_stepshelp, 
    dis_confidence, 
    dis_awareness_effect, 
    dis_awareness_count
  )

# checking that the correlations are large enought to analyze
# p value should be less than 0.05
bartlett_result <- psych::cortest.bartlett(cor(nhs))
bartlett_result # passed

# checking that the sample is sufficient
# overall MSA should be greater than 0.5, all item wise MSA should be greater than 0.5
kmo_result <- psych::KMO(cor(nhs))
kmo_result # passed, very good
# all variables are > 0.5, we don't need to evalute anything for exclusion

# checking the determinate to assess potential multicollinearity 
# looking for greater than 0.00001
det(cor(nhs)) # passed


# scree plot
psych::scree(cor(nhs), pc=FALSE)

# Principal Axis Factoring

# Testing a single factor model per the scree plot
# using an oblique rotation (items and factors are correlated)
single_factor <- psych::fa(nhs, nfactors = 1, fm = "pa", rotate = "oblimin", max.iter = 1000)

# Summary of the results
single_factor

# PA1   h2   u2 com
# dis_prep             0.66 0.44 0.56   1
# dis_soc              0.69 0.48 0.52   1
# dis_exp              0.44 0.19 0.81   1
# dis_perception       0.49 0.24 0.76   1
# dis_stepshelp        0.63 0.40 0.60   1
# dis_confidence       0.62 0.38 0.62   1
# dis_awareness_effect 0.68 0.46 0.54   1
# dis_awareness_count  0.53 0.29 0.71   1

#                 PA1
# SS loadings    2.88
# Proportion Var 0.36


# testing a 2 factor model
two_factor <- psych::fa(nhs, nfactors = 2, fm = "pa", rotate = "oblimin", max.iter = 1000)

# Summary of the results
two_factor

# PA1   PA2   h2   u2 com
# dis_prep              0.78 -0.04 0.57 0.43 1.0
# dis_soc               0.79 -0.01 0.62 0.38 1.0
# dis_exp               0.12  0.36 0.20 0.80 1.2
# dis_perception       -0.01  0.57 0.31 0.69 1.0
# dis_stepshelp        -0.04  0.77 0.56 0.44 1.0
# dis_confidence        0.11  0.58 0.43 0.57 1.1
# dis_awareness_effect  0.48  0.25 0.45 0.55 1.5
# dis_awareness_count   0.39  0.19 0.28 0.72 1.5

#                        PA1  PA2
# SS loadings           1.79 1.63
# Proportion Var        0.22 0.20
# Cumulative Var        0.22 0.43
# Proportion Explained  0.52 0.48
# Cumulative Proportion 0.52 1.00

# cronbach's alpha for PA1 in the two factor model
psych::alpha(nhs |> dplyr::select(dis_soc, dis_prep, dis_awareness_count, dis_awareness_effect)) # 0.67

# cronbach's alpha for PA2 in the two factor model
psych::alpha(nhs |> dplyr::select(dis_stepshelp, dis_confidence, dis_perception, dis_exp)) # 0.68

# Testing a 4 factor model per the scree plot
# using an oblique rotation (items and factors are correlated)
four_factor <- psych::fa(nhs, nfactors = 4, fm = "pa", rotate = "oblimin", max.iter = 1000)

# Summary of the results
four_factor

# PA1   PA2   PA3   PA4   h2   u2 com
# dis_prep              0.57  0.02  0.15  0.06 0.50 0.50 1.2
# dis_soc               0.92  0.01 -0.02  0.00 0.83 0.17 1.0
# dis_exp               0.09 -0.04  0.05  0.45 0.25 0.75 1.1
# dis_perception       -0.03  0.03 -0.02  0.69 0.47 0.53 1.0
# dis_stepshelp        -0.05  0.78  0.01  0.03 0.61 0.39 1.0
# dis_confidence        0.11  0.65  0.00 -0.03 0.48 0.52 1.1
# dis_awareness_effect  0.20  0.07  0.45  0.12 0.49 0.51 1.6
# dis_awareness_count  -0.03  0.01  0.76 -0.02 0.55 0.45 1.0

#                        PA1  PA2  PA3  PA4
# SS loadings           1.37 1.11 0.93 0.77
# Proportion Var        0.17 0.14 0.12 0.10
# Cumulative Var        0.17 0.31 0.43 0.52
# Proportion Explained  0.33 0.27 0.22 0.18
# Cumulative Proportion 0.33 0.59 0.82 1.00

# cronbach's alpha for PA1 in the four factor model
psych::alpha(nhs |> dplyr::select(dis_soc, dis_prep)) # 0.76

# cronbach's alpha for PA2 in the four factor model
psych::alpha(nhs |> dplyr::select(dis_stepshelp, dis_confidence)) # 0.69

# cronbach's alpha for PA3 in the four factor model
psych::alpha(nhs |> dplyr::select(dis_awareness_count, dis_awareness_effect)) # 0.46

# cronbach's alpha for PA4 in the four factor model
psych::alpha(nhs |> dplyr::select(dis_perception, dis_exp)) # 0.46

# the two factor model provides a more promising set of distinct factors
# looking at the factor diagram
psych::fa.diagram(two_factor)


